#https://openebs.github.io/charts/openebs-ubuntu-setup.yaml
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: openebs
  name: system-setup
  labels:
    openebs.io/component-name: system-setup
    openebs.io/version: 1.4.0
  annotations:
    command: &cmd sudo sh -c 'systemctl enable iscsid ; sudo systemctl start iscsid ; sudo systemctl status iscsid ; for d in /dev/sd[bcde] ; do umount $d ; wipefs -f -a $d ; lsblk ; done; apt -y update ; apt install -y zfsutils-linux ; zpool create zfspv-pool mirror /dev/sd[bcde] ; zfs list'
spec:
  selector:
    matchLabels:
      openebs.io/component-name: system-setup
  template:
    metadata:
      labels:
        openebs.io/component-name: system-setup
    spec:
      hostNetwork: true
      initContainers:
      - name: init-node
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - sh
          - -c
          - *cmd
        image: alpine:3.7
        securityContext:
          privileged: true
      hostPID: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
